### PR TITLE
Modernization

### PR DESCRIPTION
**Pull request by Rot127**
Work in progress...

### CODE REVIEW

**Comment by Rot127** [comment]
Commit https://github.com/vanhoefm/modwifi-tools/pull/1/commits/3496aac6b663b30abecc0bc9f4832faa04f778ac - Prevents regular failing of the unit tests.

**Comment by vanhoefm** [comment]
Apologies for not getting back to this yet! Thanks for these contributions, I'll check to get these merged later today.

**Comment by Rot127** [comment]
No problem at all!
I just closed it because I am not sure, when I will have enough time to finish it.
Unfortunately it isn't ready yet. I still need to cherry pick at least some commits from this [branch](https://github.com/Rot127/modwifi-tools/tree/krack_development) (which is a little more chaotic).
If you are fine waiting for it I will reach out to you again when I am done.

**Comment by vanhoefm** [comment]
Ah I see. I'm okay with waiting for it, once it's ready I'll double-check and merge it.

What are you using this for? I see you're implementing the Krack attack using it, which looks interesting. I can add a reference to your repository on the [ModWifi page](https://github.com/vanhoefm/modwifi#publications-and-systems-using-modwifi) with a short description (doesn't have to be something academic).

**Comment by maneshthankappan** [comment]
@Rot127 and @vanhoefm ,  I was testing the package updated by @Rot127 . Here I have downloaded package from https://github.com/Rot127/modwifi-tools/tree/modernization   then when I could compile it using "cmake CMakeLists.txt
"  .and when I did "make all" I get following error.
-------------------------------------------------------------------------------------------------------
modwifi@ubuntu:~/modwifi/tools$ make all
[  4%] Building CXX object CMakeFiles/util.dir/osal_wi.cpp.o
/home/modwifi/modwifi/tools/osal_wi.cpp: In function ‘int osal_wi_dev2phy(const char*)’:
/home/modwifi/modwifi/tools/osal_wi.cpp:153:38: error: cannot convert ‘nl_sock*’ to ‘nl_handle*’ for argument ‘1’ to ‘void nl_socket_set_cb(nl_handle*, nl_cb*)’
  nl_socket_set_cb(state.nl_sock, s_cb);
                                      ^
/home/modwifi/modwifi/tools/osal_wi.cpp:155:48: error: cannot convert ‘nl_sock*’ to ‘nl_handle*’ for argument ‘1’ to ‘int nl_send_auto_complete(nl_handle*, nl_msg*)’
  err = nl_send_auto_complete(state.nl_sock, msg);
                                                ^
/home/modwifi/modwifi/tools/osal_wi.cpp:169:32: error: cannot convert ‘nl_sock*’ to ‘nl_handle*’ for argument ‘1’ to ‘int nl_recvmsgs(nl_handle*, nl_cb*)’
   nl_recvmsgs(state.nl_sock, cb);
                                ^
make[2]: *** [CMakeFiles/util.dir/osal_wi.cpp.o] Error 1
make[1]: *** [CMakeFiles/util.dir/all] Error 2
make: *** [all] Error 2
------------------------------------------------------------------------------------------------------
Could you suggest what causes this error. I am really interested in executing this attack. Thank you.

**Comment by Rot127** [comment]
Unfortunately I don't have time anymore to continue updating the repository or this pull request.

But my guess is that you have to use an older Ubuntu version to compile it.
Try to use Ubuntu 18.04 (that's what I used back then.) Also you probably have to downgrade some wireless drives (look for the versions of 2020).
If this doesn't help, you probably have no choice but debug and rewrite some of the code.

But be prepared to solve a lot of those kind of problems. The code is pretty old and since 2015 quite a lot has changed in the wireless drivers and the Linux src.

Also try to use the krack_development branch: https://github.com/Rot127/modwifi-tools/tree/krack_development

**Comment by maneshthankappan** [comment]
@Rot127 , thank you first of all, 
at present, I am working on mathy's modwifi (Xubuntu) on Vmware. I will try with Ubuntu 18.04. so it is driver related problem. Just to clarify, I should execute "config_dongle.sh" before I execute the attack, Isn't? .

**Comment by Rot127** [comment]
`config_dongle.sh` lets you set up the interfaces to monitor mode, kill all process which operate on them (NetworkManager mostly), enables full debug output on the dongles (they log to `dmesg`) and lets you disable carrier sense on them (which is only need for the fastreply and jamming attack, if I am not mistaken).

Because you probably have to do those things quite often when developing (because unplugin and plugin in the dongles will reset all interface/dongle settings), I wrote those steps into the script.

Before you try to execute the attack you probably want to set the interface of the dongles to monitor mode and kill all processes which use those interfaces as well:
`config_dongle.sh -i <interface-name> -k`

**Comment by maneshthankappan** [comment]
@Rot127 , Thank you very much for the input. I will try the attack. and write to you updates here.

**Comment by maneshthankappan** [comment]
@Rot127 , I tried Ubuntu 18.04 as a standalone installation, its kernel was 5.4.  I could compile files. config_dongle.sh working fine. but I am getting some errors "one or more interfaces failed" when running channelmitm. I have used Mathy's release (modwifi-5.3-rc4-1.tar.gz) from https://github.com/vanhoefm/modwifi/tree/master/releases.

I have tried with ubuntu 17.04, 16.04, etc. same error happens. when I tried with Kali 2019.4, 2018.3, I could not perform standalone installation of modwifi due to several repository errors. but fighting with correcting errors. 

I am using three ALFA AWUS036NHA , as interceptor, forwarder and jammer. (I have the constant jamming code/firmware from Mathy vanhoef)

Error mainly arrives becuase of incorrect kernel I use. trying to solve it
by the by, some quries to you which I feel will help me out.
1 Hope u could successfully run the channelmitm code. Did u perform it using Ubuntu 18.04? 
2. Which release u used? Didi u use backporting?
3. Interfaces (network cards) used?
4. Any suggestions for me.
Thank you. I will update u if succeed.

**Comment by Rot127** [comment]
> 1 Hope u could successfully run the channelmitm code. Did u perform it using Ubuntu 18.04?

Yes I was able to run the code and used 18.04. But I did had the problem that the AP and client connected to each other after half a minute again. Hadn't time than to solve this problem.

> 2. Didi u use backporting?

Not really. I only compile an vulnerable version of `wpa_supplicant`. This was it.

> 3. Interfaces (network cards) used?

I used an `Atheros AR9271` or `TP-Link TL-WN722N ver. 1.1` for jamming and two `WNDA3200` for the MitM part.

> 4. Any suggestions for me.

Unfortunately not really. I eventually failed to implement the whole attack, because my allocated time for it ran out.

One problem I had was, that I connected all three dongles to a single USB-hub at once. They didn't get enough power and failed to send or receive packets. Unfortunately they didn't printed something to the log files so I solved this problem just by coincidence.

**Comment by maneshthankappan** [comment]
@Rot127 , Thank you for your input. I still struggle to implement this attack. When I run following error happens. 
--------------------------------------------------------------------------------------------------------------------------------------------------
error 1
-----------------------------------------------------------
root@manesh-uoc:/home/manesh/modwifi/tools# sudo ./channelmitm -a wlx00c0ca986cc6 -c wlx00c0ca98f913 -j wlx00c0ca98f956 -s Manesh_WiFi -d mitm.pcap --dual
Testing SeqnumStats seqence number detection...
Testing ChopState chopchop attack implementation...
Testing Michael algorithms...
Testing ACK generation...
	Pinging 00:f3:95:cd:de:5c (wlx00c0ca986cc6) with mask ff:ff:ff:ff:ff:ff
	Pinging 00:f3:95:cd:de:5c using MAC 00:c3:26:43:82:09(random)
	Pinging 00:f3:95:cd:de:5d (wlx00c0ca986cc6) with mask ff:ff:ff:ff:ff:fe
	Pinging 00:f3:95:cd:de:5d using MAC 00:01:34:85:d0:51(random)
	Pinging 00:9a:f9:1b:a5:e6 (wlx00c0ca98f913) with mask ff:ff:ff:ff:ff:ff
	Pinging 00:9a:f9:1b:a5:e6 using MAC 00:38:43:30:32:65(random)
	Pinging 00:9a:f9:1b:a5:e7 (wlx00c0ca98f913) with mask ff:ff:ff:ff:ff:fe
	Pinging 00:9a:f9:1b:a5:e7 using MAC 00:a3:5c:be:1c:38(random)
Testing sequence number injection for management frames (probe responses)...
	Injecting sequence number 0xc29 from 00:90:0f:cd:5e:ed (wlx00c0ca986cc6)
	Injecting sequence number 0xb6e from 00:21:13:6d:a3:1c (wlx00c0ca98f913)
	FAILURE: Injected sequence number 0xb6e but captured 0x140 (injected by wlx00c0ca98f913)
One or more test failed on the given interfaces
-------------------------------------------------------------------------------------------------------------------------------------
error2
-----------------------------------------------------------------------------------------------------------------------------
root@manesh-uoc:/home/manesh/modwifi/tools# sudo ./channelmitm -a wlx00c0ca986cc6 -c wlx00c0ca98f913 -j wlx00c0ca98f956 -s Manesh_WiFi -d mitm.pcap --dual
Testing SeqnumStats seqence number detection...
Testing ChopState chopchop attack implementation...
Testing Michael algorithms...
Testing ACK generation...
	Pinging 00:18:ad:4e:94:f2 (wlx00c0ca986cc6) with mask ff:ff:ff:ff:ff:ff
	Pinging 00:18:ad:4e:94:f2 using MAC 00:c6:d8:9e:f0:bf(random)
Failed to ping wlx00c0ca986cc6
One or more test failed on the given interfaces
----------------------------------------------------------------------------------------------------------------------------------
I have debugged the code, I have tested this code on more than 10 linux versions, such as Kali and Ubuntu with kernal 4.4 or 5.3.
I doubt, its because of some firmware issues, or masking of MAC addresses. Could you give any suggestions? or share your thinking so that I can solve these errors. Thank you.

**Comment by Rot127** [comment]
@maneshthankappan What I did back then was simply to read the `dmesg` logs, find out where the errors came from and patched them.
Sorry, that was probably not the help you were looking for, but I have unfortunately no other advise for you.

**Comment by maneshthankappan** [comment]
@Rot127 , Thank you. I will check dmesg, 
I have debugged the code and found that following error comes during,performing "unit_tests_interface" tests. Here when  the "test_ack_generation" is called, I get error as

"Failed to open /sys/kernel/debug/ieee80211/phy2/ath9k_htc/macaddr for writing"  

Is it related to any firmware issue.? Any suggestions. Because of this, I am unable to move. If I comment tests, code works till "Started Attack" and I am unable to see any further messages.

**Comment by Rot127** [comment]
Besides that it looks like a permission problem, are you using vanhoefs firmware for the dongles?
https://github.com/vanhoefm/modwifi-ath9k-htc
Otherwise I have no idea.

**Comment by maneshthankappan** [comment]
Yes. I am using the same, Once again, I will verify and compile it and let you know.

**Comment by maneshthankappan** [comment]
@Rot127 , Hello, I was experimenting these days. Finally able to run the code but partially. I am on Xubuntu 16.04 with kernel "4.4.0-210-generic". With this I was able to install required dependencies (as per https://github.com/vanhoefm/modwifi#installation-and-source-code) and compile files.
and I use https://github.com/vanhoefm/modwifi/blob/master/releases/modwifi-4.4-1.tar.gz  package.
In modwif tools folder, I replace necessary files such as channelmitm.cpp, osal_wi.cpp, probe_requests.h, config_dongle.sh as you have updated those files.

Following is the output I receive.
----------------------------------------------
root@manesh-uoc:/home/manesh/modwifi/tools# ./channelmitm -a wlx00c0ca98f956 -c wlx00c0ca98f913 -j wlx00c0ca986cc6 -s testnetwork -d mitm.pcap --dual
Testing SeqnumStats seqence number detection...
Testing ChopState chopchop attack implementation...
Testing Michael algorithms...
Tests complete, starting channelmitm...
AP Channel:	1
CLONE channel:	13
Cloned SSID:	testnetwork
Cloned BSSID:	C0:4A:00:33:3B:62
[18:23:18]  Started continuous jammer (cont jam)
[18:23:18]  Started attack!
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
[18:23:19]  CLONE    : 43    dc:1b:a1:fb:e5:c8 to c0:4a:00:33:3b:62 (U  Mngmt / Auth      ) -> AP     | MiTM'ed 
.
[18:23:19]  AP       : 0     c0:4a:00:33:3b:62 to dc:1b:a1:fb:e5:c8 (UR Data  / QoS Data  ) -> CLONE  | EAPOL 1
[18:23:19]  AP       : 1     c0:4a:00:33:3b:62 to dc:1b:a1:fb:e5:c8 (UR Data  / QoS Data  ) -> CLONE  | EAPOL 1
[18:23:19]  CLONE    : 0     dc:1b:a1:fb:e5:c8 to c0:4a:00:33:3b:62 (UR Data  / QoS Data  ) -> AP     | EAPOL 2
[18:23:19]  AP       : 2     c0:4a:00:33:3b:62 to dc:1b:a1:fb:e5:c8 (UR Data  / QoS Data  ) -> CLONE  | EAPOL 1
[18:23:19]  AP       : 3     c0:4a:00:33:3b:62 to dc:1b:a1:fb:e5:c8 (UR Data  / QoS Data  ) -> CLONE  | EAPOL 1
[18:23:19]  CLONE    : 101   dc:1b:a1:fb:e5:c8 to c0:4a:00:33:3b:62 (UR Data  / QoS Data  ) -> AP     | EAPOL 2
[18:23:19]  CLONE    : 1     dc:1b:a1:fb:e5:c8 to c0:4a:00:33:3b:62 (UR Data  / QoS Data  ) -> AP     | EAPOL 2
[18:23:19]  CLONE    : 2     dc:1b:a1:fb:e5:c8 to c0:4a:00:33:3b:62 (U  Data  / QoS Data  ) -> AP     | EAPOL 2
[18:23:20]  CLONE    : 103   dc:1b:a1:fb:e5:c8 to c0:4a:00:33:3b:62 (UR Data  / QoS Data  ) -> AP     | EAPOL 2
[18:23:20]  CLONE    : 104   dc:1b:a1:fb:e5:c8 to c0:4a:00:33:3b:62 (U  Data  / QoS Data  ) -> AP     | EAPOL 2
.
.
.
.
.
.
.
.
.
.
[18:23:20]  AP       : 4     c0:4a:00:33:3b:62 to dc:1b:a1:fb:e5:c8 (UR Data  / QoS Data  ) -> CLONE  | EAPOL 1
[18:23:20]  AP       : 1132  c0:4a:00:33:3b:62 to dc:1b:a1:fb:e5:c8 (UR Data  / QoS Data  ) -> CLONE  | EAPOL 1
[18:23:20]  AP       : 1133  c0:4a:00:33:3b:62 to dc:1b:a1:fb:e5:c8 (UR Data  / QoS Data  ) -> CLONE  | EAPOL 1
.
.
.
.
^C
Stopping AP cloning...
Stopping jammer...
-----------------------------------------------------------
In the above output, Why "." comes frequently?, Sometimes I get "." only. When I debugged the code, I understand that its because time difference between current beacon vs next beacon of the target router. Did you get these errors ever?
Below I insert the code of from channelmitm function of channelmitm.cpp
-----------------------------------------------
if (timespec_cmp(&time_next_beacon, &now) <= 0)
		{
			printf(".\n");

			// FIXME: This should actually be done in hardware!
			fixedparams->timestamp = timespec_to_64us(&now);
			// REMARK: When using a different
			if (osal_wi_write(clone, global.beaconbuf, global.beaconlen) < 0)
				return -1;

			// Determine when we should send the next beacon
			do {
				timespec_add_usec(&time_next_beacon, fixedparams->interval * TIMEUNIT_USEC);
			} while (timespec_cmp(&time_next_beacon, &now) <= 0);
		}
----------------------------------------
How can i rectify this issue? I keep my router 4-5 meter away from the attack room/primises.
I also need to clarify the following. 

1. After   compiling fimware as per  https://github.com/vanhoefm/modwifi-ath9k-htc, , we get  two fimware, *.fw images which I copy to my /lib/firmware folder. Is this correct?  or should I copy this to /lib/fimware/ath9k_htc folder?

Thank you for considering my doubts.

**Comment by Rot127** [comment]
> should I copy this to /lib/fimware/ath9k_htc folder?

Yes, move them to `/lib/firmware/ath9k_htc`

> Why "." comes frequently?, Sometimes I get "." only.

The dot appears every time a beacon is sent from your fake AP. If your target client does not initiates a handshake after that beacon, it probably ignores it for some reason.
Here are some ideas why this happens:

- The target client is still associated with the real AP, because something went wrong with the jamming.
- The beacon packet is received by the target client and it responds, but the fake client sends the incorrect probe request to the AP.
  With incorrect probe request I mean that each dongle has some specific hardware properties it embeds in the probe request as tags. If you use your `TL-WN722N` to send out a probe request with `AWUS036NHA`-tags set, the handshake will fail sometimes. At least this happened to me.

Check out the recorded probe request tags in my [probe_requests.h](https://github.com/Rot127/modwifi-tools/blob/krack_development/probe_requests.h) and set the one in the code, according to your dongle on the fake client side.


When I got similar problems back then (though I can't remember how I solved them specifically), I used two other dongles (one for each channel) to sniff the traffic on both channels with `wireshark` to see what is going on.
This is really helpful because you see directly whether you target client switched the channel and which packages get a response and which not.

Also note that the AP does not answer with a EAPOL 3 package in your logs. Maybe check out what is going on there.

**Comment by maneshthankappan** [comment]
@Rot127 , Great input. thank you so much for your time.

Yes. I already moved fimware images to /lib/firmware/ath9k_htc. and run channelmitm.

Yes. your ideas are correct. Here, when I checked, the constant jamming is not working actually although I  copied the compiled firmware images(htc_7010.fw & htc_9271.fw ) to /lib/firmware folder.** 
(_This is given by vanhoef as constant jamming is not public_,). 
When I checked jamming individually, reactive jam works perfectly. On the other hand, constant jam code is initiated, but there is no jamming on specific channel. I think, this is the reason when we run channelmitm, the clients do not connect to the fake AP and hence  "." displayed. 

**Just to confirm, I should copy the compiled firmware images(htc_7010.fw & htc_9271.fw ) from vanhoef, to /lib/firmware folder. right?**
I already did it, but why constant jamming do not work. Any other things to note/perform.?

I have TL-WN722N (v1.1) and AWUS036NHA. Here, I use two TL-WN722N to as interceptor and forwarder and  AWUS036NHA as jammer. I will set the tags of TL-WN722N in your  probe_requests.h. and let you know.


I will also sniff the two channels using other dongles and study what happens. 

Thank you again for the support.

**Comment by Rot127** [comment]
> I should copy the compiled firmware images(htc_7010.fw & htc_9271.fw ) to /lib/firmware folder. right?

On my system (debian) the firmware files are in `/lib/firmware/ath9k_htc/`. If you use Xubuntu they probably belong there as well.
So, copy the files to the directory `/lib/firmware/ath9k_htc/`.

>  I will set the tags of TL-WN722N in your probe_requests.h

You don't have to add the tags. They are already there.

Just set the one for the fake client side dongle here:

https://github.com/Rot127/modwifi-tools/blob/6d3422464f0d7f19d76063bc209ba395f58d1f74/channelmitm.cpp#L1369-L1374

**Comment by maneshthankappan** [comment]
Thank you. Things are clear to me. I will experiment and keep you posted.

**Comment by maneshthankappan** [comment]
@Rot127 . Excited I am! 
Finally  the code works. 
Screenshot_2021-08-03_14-45-29
Screenshot_2021-08-03_14-44-56
Screenshot_2021-08-03_14-58-03
Screenshot_2021-08-03_15-03-07



Thanks a million for your kind consideration of my quires. Continuous jams works perfect. My both clients connected to cloned AP/fake AP. However, I did not get the MIC key that I have to solve. Did u get MIC key at end? 

Whatsoever, It was nice working with this experiment. learned a lot regarding firmware, kernels, etc. Your contributions (modernization) to initial codes of vanhoef was very useful in fixing bugs, especially, handling probe responses. The config_dongle.sh script is also so handy. Thanks Rot127.

@vanhoefm , Hats off to you.

**Comment by Rot127** [comment]
Great to here that! I am very happy that I could help.

> Did u get MIC key at end?
Unfortunately not. My allocated time for it ran out before finishing the KRACK implementation. But as you said as well, I was learning quite a lot on the way.

If you want to dive into it further you can take a look at the KrackState.cpp/.h files in my krack_development branch. 
The implementation is still missing some parts and you probably have to debug it. Though maybe it is of some help.

**Comment by Rot127** [comment]
I close this pull request here since I won't add anything new to it.
Hopefully our discussion is of some help to others.

**Pull request closed without merging**
